// Cloudflare Worker: add KMA_API_KEY and DATA_GO_KR_API_KEY as Worker Secrets.
const BEACHES = {
  haeundae: { name: "해운대해수욕장", lat: 35.158698, lng: 129.160384 },
  gwangalli: { name: "광안리해수욕장", lat: 35.153169, lng: 129.118666 },
  songjeong: { name: "송정해수욕장", lat: 35.179807, lng: 129.200540 },
  songdo: { name: "송도해수욕장", lat: 35.076207, lng: 129.020967 },
  dadaepo: { name: "다대포해수욕장", lat: 35.046033, lng: 128.967720 },
  ilgwang: { name: "일광해수욕장", lat: 35.261821, lng: 129.233831 },
  imrang: { name: "임랑해수욕장", lat: 35.318771, lng: 129.267088 }
};
const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET, OPTIONS", "Access-Control-Allow-Headers": "Content-Type" };
const unavailable = (source, message) => ({ status: "unavailable", source, message });
const error = (source, message) => ({ status: "error", source, message });
const koreaNow = () => new Date(Date.now() + 9 * 3600000);
const stamp = d => `${d.toISOString().slice(0, 10).replaceAll("-", "")} ${String(d.getUTCHours()).padStart(2, "0")}:${String(d.getUTCMinutes()).padStart(2, "0")}`;
function grid(lat, lng) { const r=6371.00877,g=5,d=Math.PI/180,s1=30*d,s2=60*d,sn=Math.log(Math.cos(s1)/Math.cos(s2))/Math.log(Math.tan(Math.PI/4+s2/2)/Math.tan(Math.PI/4+s1/2)),sf=Math.pow(Math.tan(Math.PI/4+s1/2),sn)*Math.cos(s1)/sn,ra=r/g*sf/Math.pow(Math.tan(Math.PI/4+lat*d/2),sn),th=(lng-126)*d; return { nx:Math.floor(ra*Math.sin(th*sn)+43.5), ny:Math.floor(-ra*Math.cos(th*sn)+136.5) }; }
function ultraBase() { const d=koreaNow(); d.setUTCMinutes(d.getUTCMinutes()-45); return { date:d.toISOString().slice(0,10).replaceAll("-", ""), time:`${String(d.getUTCHours()).padStart(2,"0")}00` }; }
function villageBase() { const d=koreaNow(); d.setUTCMinutes(d.getUTCMinutes()-15); const hours=[23,20,17,14,11,8,5,2]; let h=hours.find(x=>x<=d.getUTCHours()); if(h===undefined){d.setUTCDate(d.getUTCDate()-1);h=23;} return { date:d.toISOString().slice(0,10).replaceAll("-", ""), time:`${String(h).padStart(2,"0")}00` }; }
function condition(sky, pty) { const p=Number(pty); if(p===1||p===4) return "rain"; if(p===2||p===3) return "snow"; if(Number(sky)===1) return "sun"; if(Number(sky)===3) return "cloud"; return "overcast"; }
function params(key, base, point, rows="1000") { return new URLSearchParams({ serviceKey:key, pageNo:"1", numOfRows:rows, dataType:"JSON", base_date:base.date, base_time:base.time, nx:String(point.nx), ny:String(point.ny) }); }
async function json(url) { const r=await fetch(url); if(!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }
async function weather(env, beach) { if(!env.KMA_API_KEY) return unavailable("기상청", "KMA_API_KEY Secret이 설정되지 않았습니다."); const point=grid(beach.lat,beach.lng), u=ultraBase(), v=villageBase(); try { const now=await json(`https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst?${params(env.KMA_API_KEY,u,point)}`); const nowItems=now?.response?.body?.items?.item; if(now?.response?.header?.resultCode!=="00"||!Array.isArray(nowItems)) throw new Error("기상청 실황 응답 오류"); const t=Number(nowItems.find(x=>x.category==="T1H")?.obsrValue); if(!Number.isFinite(t)) throw new Error("현재 기온 미제공"); const forecast=await json(`https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst?${params(env.KMA_API_KEY,v,point)}`); const list=forecast?.response?.body?.items?.item; if(forecast?.response?.header?.resultCode!=="00"||!Array.isArray(list)) throw new Error("기상청 예보 응답 오류"); const keys=[...new Set(list.filter(x=>x.category==="TMP").map(x=>`${x.fcstDate}${x.fcstTime}`))].sort().slice(0,6); const hourly=keys.map(k=>{const one=c=>list.find(x=>x.category===c&&`${x.fcstDate}${x.fcstTime}`===k)?.fcstValue; const temp=Number(one("TMP")), pop=Number(one("POP")); return Number.isFinite(temp)?{ time:`${k.slice(8,10)}:${k.slice(10,12)}`, temperature:temp, rainProbability:Number.isFinite(pop)?pop:null, condition:condition(one("SKY"),one("PTY")) }:null;}).filter(Boolean); const first=hourly[0]; return { status:"ok", source:"기상청", temperature:t, rainProbability:first?.rainProbability??null, condition:first?.condition??null, observedAt:`${u.date.slice(0,4)}.${u.date.slice(4,6)}.${u.date.slice(6)} ${u.time.slice(0,2)}:00`, hourly }; } catch(e) { return error("기상청", "날씨 정보를 불러오지 못했습니다."); } }
function num(o, names) { for(const n of names){const v=o[n];const x=Number(v);if(Number.isFinite(x))return x;} return null; }
function str(o,names) { for(const n of names)if(o[n]!=null&&String(o[n]).trim())return String(o[n]);return null; }
function haversine(a,b){const r=6371,d=Math.PI/180,dl=(b.lat-a.lat)*d,do_=(b.lng-a.lng)*d,x=Math.sin(dl/2)**2+Math.cos(a.lat*d)*Math.cos(b.lat*d)*Math.sin(do_/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function itemsOf(j){const b=j?.response?.body;return b?.items?.item||b?.items||b?.item||[];}
async function parking(env, beach) { if(!env.DATA_GO_KR_API_KEY) return unavailable("부산시설공단", "DATA_GO_KR_API_KEY Secret이 설정되지 않았습니다."); const p=new URLSearchParams({serviceKey:env.DATA_GO_KR_API_KEY,pageNo:"1",numOfRows:"1000",dataType:"JSON"}); try { const [listJ,infoJ]=await Promise.all([json(`https://apis.data.go.kr/B552587/ParkingInfoService_v2/getParkingList_v2?${p}`),json(`https://apis.data.go.kr/B552587/ParkingInfoService_v2/getParkingInfoList_v2?${p}`)]); const list=itemsOf(listJ),infos=itemsOf(infoJ); if(!Array.isArray(list)||!Array.isArray(infos)) throw new Error("주차 API 응답 오류"); const live=new Map(infos.map(x=>[str(x,["parkingCode","pkCode","parkCode","id","code"]),x])); const parks=list.map(x=>{const code=str(x,["parkingCode","pkCode","parkCode","id","code"]),l=live.get(code)||infos.find(y=>str(y,["parkingName","parkName","name"])===str(x,["parkingName","parkName","name"])); const lat=num(x,["latitude","lat","yCoord","y"]),lng=num(x,["longitude","lng","xCoord","x"]),total=num(l||x,["totalSpace","total","totalCnt","capacity","parkSpace"]),available=num(l||x,["availableSpace","available","availableCnt","remainCnt","freeSpace"]); if(!l||lat===null||lng===null||total===null||available===null||total<0||available<0)return null; return {name:str(x,["parkingName","parkName","name"]),available,total,updatedAt:str(l,["updateDate","updatedAt","lastUpdate","regDate"]),distanceKm:haversine(beach,{lat,lng})};}).filter(Boolean).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,5); return parks.length?{status:"ok",source:"부산시설공단",items:parks}:{status:"unavailable",source:"부산시설공단",message:"위치와 실시간 가능 대수가 함께 제공된 주차장을 찾지 못했습니다."}; } catch(e) { return error("부산시설공단", "주차 정보를 불러오지 못했습니다."); } }
export default { async fetch(request, env) { if(request.method==="OPTIONS") return new Response(null,{headers:cors}); const u=new URL(request.url); if(u.pathname!=="/beach") return Response.json({error:"Not found"},{status:404,headers:cors}); const beach=BEACHES[u.searchParams.get("beach")]||BEACHES.haeundae; const [weatherData,parkingData]=await Promise.all([weather(env,beach),parking(env,beach)]); return Response.json({beach:beach.name,weather:weatherData,water:unavailable("공식 해양관측", "수온 정보 미제공"),parking:parkingData,visitors:unavailable(null,"실시간 이용객 데이터 미제공")},{headers:{...cors,"Cache-Control":"public, max-age=60"}}); } };
